name: Compile LaTeX with LuaLaTeX
on:
  push:
    paths:
      - 'Notes/notesLaTeX/**'
      - 'GuiasExamen/E3/**'
  workflow_dispatch:
permissions:
  contents: write
  pages: write
  id-token: write
jobs:
  builNotes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project repo
        uses: actions/checkout@v6
      - name: Checkout HomeworkTemplate
        uses: actions/checkout@v6
        with:
          repository: MarcosLopezM/HomeworkTemplate
          path: hw-template
      - name: Move template
        run: |
          cp -r hw-template Notes/notesLaTeX/
          cp -r hw-template GuiasExamen/E3/
          cp -r Notes/notesLaTeX/hw-template/fonts Notes/notesLaTeX/
          cp -r GuiasExamen/E3/hw-template/fonts GuiasExamen/E3/
      - name: Build PDF with LuaLaTeX
        uses: xu-cheng/latex-action@v4
        with:
          root_file: |
            Notes/notesLaTeX/main.tex
            GuiasExamen/E3/main.tex
          texlive_version: 2026
          work_in_root_file_dir: true
          latexmk_shell_escape: true
          latexmk_use_lualatex: true
        env:
          TEXINPUTS: ".:./hw-template//:"
      - name: Create output folder
        id: build
        run: |
          mkdir -p build/
          mv Notes/notesLaTeX/main.pdf build/notas.pdf
          mv GuiasExamen/E3/main.pdf build/guiaE3.pdf
          cat <<EOF > build/index.html
          <!DOCTYPE html>
          <html lang="en">
          <head>
              <meta charset="UTF-8">
              <meta name="viewport" content="width=device-width, initial-scale=1.0">
              <title>My Compiled Documents</title>
              <style>
                  body { font-family: sans-serif; padding: 2rem; max-width: 600px; margin: auto; }
                  ul { line-height: 1.6; }
                  a { text-decoration: none; color: #0366d6; font-size: 1.2rem; }
                  a:hover { text-decoration: underline; }
              </style>
          </head>
          <body>
              <h1>Available Documents</h1>
              <ul>
                  <li><a href="notas.pdf">Notas de clase</a></li>
                  <li><a href="guiaE3.pdf">Guía del Tercer Examen Parcial</a></li>
              </ul>
          </body>
          </html>
          EOF
      - name: Ensure PDF was compiled
        run: |
          test -f build/notas.pdf
          test -f build/guiaE3.pdf
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build
          branch: gh-pages
